dependencies {
    implementation project(':shared:common')
    implementation project(':shared:security')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.apache.poi:poi:5.3.0'
    implementation 'org.apache.poi:poi-ooxml:5.3.0'
    implementation 'com.opencsv:opencsv:5.9'
}