services:
  - type: web
    name: vandinh-api
    rootDir: backend
    plan: free
    runtime: docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
