services:
  - type: web
    name: vandinh-api
    rootDir: backend
    plan: free   # hoặc starter, tùy chọn
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false