export type IGetProductDetailResponse = {
   productId: string,
   productName: string,
   productDescription: string,
   productImage: string[],
   productVolume: string,
   productUnit: string,
   productCode: string,
   productQuantity: number,
   discount: number,
   productPrice: number,
   supplierName: string,
   colorName: string,
   colorCode: string,
   categoryName: string,
   createAt: string,
   updateAt: string,
}