export const QueryKeys = {
SERVICE: 'service',
LANGUAGE:'language',
INVOICE:'invoice',
ONSHIFT:'onshift',
OFFSHIFT:'offshift',
GET_USERS:'get all users',
GET_MY_PROFILE:' get my profile',
UPDATE_USER: 'Update User',
DELETE_USER: 'Delete User',
GET_SUPPLIER: 'Get all suppliers',
CREATE_SUPPLIER: 'Create Suppliers',
GET_CATEGORY: 'Get all categories',
GET_ALL_PRODUCT: 'Get All Products',
}