export const QueryKeys = {
SERVICE: 'service',
LANGUAGE:'language',
INVOICE:'invoice',
ONSHIFT:'onshift',
OFFSHIFT:'offshift',
GET_USERS:'get all users',
GET_MY_PROFILE:' get my profile',
UPDATE_USER: 'Update User',
DELETE_USER: 'Delete User',
GET_SUPPLIER: 'Get all suppliers',
CREATE_SUPPLIER: 'Create Suppliers',
GET_CATEGORY: 'Get all categories',
GET_ALL_PRODUCT: 'Get All Products',
GET_PRODUCT_DETAIL: 'Get product detail',
GET_SUPPLIER_SELECTION: 'Get Supplier Selection',
GET_CATEGORY_SELECTION: 'Get Category Selection',
GET_USER_SELECTION: 'Get User Selection',
GET_PRODUCT_SELECTION: 'Get Product Selection',
GET_COLOR_SELECTION: 'Get Color Selection',
GET_COLORS: 'Get All Colors',
GET_ALL_ORDERS: 'Get All Orders',
GET_ORDER_DETAIL: 'Get Order Detail',
GET_USER_ORDER_HISTORY: 'Get User Order History',
GET_NOTIFICATIONS: 'Get Notifications',
GET_ALL_NOTIFICATIONS: 'Get All Notifications',
GET_USER_ONLINE_STATUS: 'Get User Online Status',
GET_PURCHASE_ORDERS: 'Get Purchase Orders',
GET_PURCHASE_ORDER_DETAIL: 'Get Purchase Order Detail',
GET_INVENTORY: 'Get Inventory',
GET_PURCHASE_DETAIL: 'Get Purchase Detail',
GET_ALL_DIARY: 'Get All Diary',
GET_DIARY_DETAIL: 'Get Diary Detail',
GET_UNREAD_COUNT_NUM_NOTIFICATIONS: 'Get UnRead Count Num Notifications'
}