version: '3.9'

services:
  app:
    build: .
    # hoặc image: your-spring-app:latest nếu đã build/push
    ports:
      - "8080:8080"  # host:container, thay nếu cần
    env_file:
      - ./.env      # Load tất cả env từ file .env vào container
    restart: unless-stopped
    # depends_on: nếu có DB khác (ví dụ mysql/postgres)
    # healthcheck: nếu cần