name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: testdb
      DB_USERNAME: test
      DB_PASSWORD: test

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USERNAME; do
            sleep 5
          done
          echo "PostgreSQL is ready!"

      - name: Build & Test with Maven
        run: mvn clean verify

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run Docker Compose
        run: docker compose up -d --build
